# Generated by Django 4.1.4 on 2023-03-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "website_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "title_seperator",
                    models.CharField(
                        blank=True,
                        choices=[("-", "-"), ("|", "|"), (",", ",")],
                        default="-",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "website_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "website_author",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "featured_image",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/site_configuration/"
                    ),
                ),
                (
                    "fav_icon",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/site_configuration/"
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/site_configuration/"
                    ),
                ),
                (
                    "footer_copyright",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Configurations",
            },
        ),
    ]
