# Generated by Django 4.1.4 on 2023-03-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuro", "0002_alter_configuration_website_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
