# Generated by Django 4.1.4 on 2023-03-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuro", "0003_configuration_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="skin_color",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="configuration",
            name="skin_color_dark",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="configuration",
            name="skin_color_light",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
