services:

  automagic:
    #build: .
    container_name: automagic
    image: mabdelgawad94/automagic_developer:latest
    env_file:
      - .env
      - .secrets
    pull_policy: always
    restart: always
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true