version: '3.9'

services:
  nginx-certbot:
    image: nginx:latest
    container_name: nginx-certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Nginx server config
      - ./nginx/ssl/:/etc/letsencrypt  # Store SSL certificates
      - ./nginx/challenges:/var/www/certbot  # Store challenges
    entrypoint: >
      /bin/sh -c "
      if [ ! -f /etc/letsencrypt/live/automagicdeveloper.com/fullchain.pem ]; then
        certbot --nginx --non-interactive --agree-tos --email muhammadabdelgawwad@gmail.com -d automagicdeveloper.com -d www.automagicdeveloper.com;
      fi;
      nginx -g 'daemon off;'
      "
    depends_on:
      - app

  app:
    build:
      context: .
    container_name: django-app
    environment:
      - DJANGO_SETTINGS_MODULE=automagic_developer.settings
    ports:
      - "8000:8000"
