services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs  # Mount directory for certificates
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  automagic:
    build:
      context: .
    container_name: automagic
    environment:
      - DJANGO_SETTINGS_MODULE=automagic_developer.settings
    ports:
      - "8000:8000"