services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:rw  # Mount certificates for Nginx and Certbot
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Nginx configuration
    depends_on:
      - django-app

  django-app:
    build:
      context: .
    container_name: django-app
    environment:
      - DJANGO_SETTINGS_MODULE=automagic_developer.settings
    ports:
      - "8000:8000"