services:
  app:
    build:
      context: .
    container_name: django-app
    environment:
      - DJANGO_SETTINGS_MODULE=automagic_developer.settings
    volumes:
      - ./.env:/website/.env:ro  # Ensure .env is at the root level
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Custom server config
      - certs:/etc/letsencrypt  # Persistent volume for SSL certs
      - certbot-challenges:/var/www/certbot  # Certbot challenge directory

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certbot-challenges:/var/www/certbot
    entrypoint: >
      /bin/sh -c "
        trap exit TERM;
        while :; do 
          certbot renew --webroot -w /var/www/certbot;
          sleep 12h & wait $!;
        done
      "

volumes:
  certs:
  certbot-challenges:
