version: '3.9'

services:
  nginx-certbot:
    build:
      context: ./nginx
    container_name: nginx-certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  app:
    build:
      context: .
    container_name: django-app
    environment:
      - DJANGO_SETTINGS_MODULE=automagic_developer.settings
    ports:
      - "8000:8000"