services:
  app:
    build:
      context: .
    container_name: django-app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=automagic_developer.settings

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certs:/etc/letsencrypt
      - certbot-challenges:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certbot-challenges:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 24h & wait $!; certbot renew --webroot -w /var/www/certbot; done'"

volumes:
  certs:
  certbot-challenges:
