services:
  app:
    build:
      context: .
    container_name: django-app
    environment:
      - DJANGO_SETTINGS_MODULE=automagic_developer.settings
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/website/.env:ro  # Ensure .env is mounted
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certs:/etc/letsencrypt  # Persistent volume for SSL certs
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certbot-challenges:/var/www/certbot
    entrypoint: >
      /bin/sh -c "
        if [ ! -f /etc/letsencrypt/live/automagicdeveloper.com/fullchain.pem ]; then
          certbot certonly --webroot -w /var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d automagicdeveloper.com -d www.automagicdeveloper.com;
        fi;
        trap exit TERM;
        while :; do 
          certbot renew --webroot -w /var/www/certbot;
          sleep 24h & wait $!;
        done
      "

volumes:
  certs:
  certbot-challenges:
