services:

  automagic:
    build: .
    container_name: automagic
    image: mabdelgawad94/automagic_developer:latest
    restart: always
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true