# Generated by Django 4.1.4 on 2023-03-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_intro", models.CharField(blank=True, max_length=250, null=True)),
                ("hero_title", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "hero_sub_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "hero_paragraph",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "hero_button_text",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "hero_button_icon",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "hero_button_url",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "hero_animation_file",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/home_configuration/"
                    ),
                ),
                (
                    "skills_section_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "projects_section_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "projects_button_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "projects_button_icon",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "blog_section_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "blog_button_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "blog_button_icon",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "contact_section_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "contact_section_paragraph",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "contact_button_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "contact_button_icon",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Configurations",
            },
        ),
    ]
