# Generated by Django 4.1.4 on 2023-03-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_configuration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="configuration",
            old_name="blog_button_title",
            new_name="blog_button_text",
        ),
        migrations.RenameField(
            model_name="configuration",
            old_name="contact_button_title",
            new_name="contact_button_text",
        ),
        migrations.RenameField(
            model_name="configuration",
            old_name="projects_button_title",
            new_name="projects_button_text",
        ),
        migrations.AlterField(
            model_name="configuration",
            name="contact_section_paragraph",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="hero_paragraph",
            field=models.TextField(blank=True, null=True),
        ),
    ]
