# Generated by Django 4.1.4 on 2022-12-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
