# Generated by Django 4.1.4 on 2023-01-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='summary',
        ),
    ]
