# Generated by Django 4.1.4 on 2023-01-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_project_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='python', max_length=250),
            preserve_default=False,
        ),
    ]
