# Generated by Django 4.1.4 on 2023-03-17 09:36

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("portfolio", "0007_alter_project_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="skills",
        ),
        migrations.AddField(
            model_name="project",
            name="skills",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
