# Generated by Django 4.1.4 on 2023-03-17 09:44

from django.db import migrations
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("portfolio", "0008_remove_project_skills_project_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="skills",
            field=portfolio.models.SkillsTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Skills",
            ),
        ),
    ]
